# -*- coding: utf-8 -*-
"""Agente Planejador de Rotas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lENTzP44u4DqcJOEHZy-s3EEZf5kScr9
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

# Commented out IPython magic to ensure Python compatibility.
# Instalar Framework ADK de agentes do Google ################################################
# %pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

from datetime import date
from IPython.display import display, Markdown as md  # Mantendo para exibição formatada

####################################################
# --- Agente 1: Buscador de Informações de Rotas --- #
####################################################
def agente_buscador(localizacao, preferencias):
    buscador = Agent(
        name="agente_buscador_rotas",
        model="gemini-2.0-flash",
        instruction=f"""
        Você é um assistente de pesquisa especializado em encontrar informações relevantes para a criação de rotas de caminhada e corrida.
        Sua tarefa é utilizar mecanismos de busca (como o Google Search) para localizar informações sobre:
        - Trilhas, parques, áreas verdes e ruas tranquilas adequadas para caminhada e corrida na localização fornecida: {localizacao}.
        - Preferências do usuário, como tipo de terreno (plano, montanhoso), nível de dificuldade desejado (fácil, moderado, difícil), distância aproximada e tipos de paisagens preferidas (natureza, urbana, beira-mar, etc.): {preferencias}.
        - Informações sobre segurança, acessibilidade (transporte público, estacionamento) e comodidades (banheiros, bebedouros) nas áreas identificadas.
        Priorize informações de fontes confiáveis como sites de prefeituras, guias de trilhas, aplicativos de corrida/caminhada e relatos de usuários.
        Tente encontrar pelo menos 3-5 opções de locais ou rotas que pareçam promissoras com base nos critérios fornecidos.
        """,
        description="Agente que busca informações sobre locais para rotas.",
        tools=[google_search]
    )

    entrada_do_agente_buscador = f"Localização: {localizacao}\nPreferências: {preferencias}"
    locais_encontrados = call_agent(buscador, entrada_do_agente_buscador)
    return locais_encontrados

#####################################################
# --- Agente 2: Planejador de Rotas Personalizadas --- #
#####################################################
def agente_planejador(localizacao, preferencias, locais_encontrados):
    planejador = Agent(
        name="agente_planejador_rotas",
        model="gemini-2.0-flash",
        instruction=f"""
        Você é um planejador de rotas de caminhada e corrida especializado em criar percursos personalizados.
        Com base nos locais e informações encontrados pelo agente buscador ({locais_encontrados}), e considerando a localização do usuário ({localizacao}) e suas preferências ({preferencias}), sua tarefa é:
        - Detalhar as características de cada local promissor (tipo de terreno, elevação, sombra, segurança, etc.).
        - Utilizar o Google Search para obter informações mais detalhadas sobre rotas existentes nesses locais, incluindo mapas, distâncias e avaliações de outros usuários.
        - Combinar informações de diferentes fontes para propor pelo menos 2-3 sugestões de rotas personalizadas que atendam às preferências do usuário.
        - Para cada rota sugerida, inclua detalhes como:
            - Descrição do percurso.
            - Distância aproximada.
            - Nível de dificuldade estimado.
            - Pontos de interesse ao longo do caminho.
            - Sugestões de como chegar ao ponto de partida (transporte público, carro).
            - Considerações de segurança.
        """,
        description="Agente que planeja rotas personalizadas.",
        tools=[google_search]
    )

    entrada_do_agente_planejador = f"Localização: {localizacao}\nPreferências: {preferencias}\nLocais encontrados: {locais_encontrados}"
    rotas_planejadas = call_agent(planejador, entrada_do_agente_planejador)
    return rotas_planejadas

############################################
# --- Agente 3: Otimizador de Rotas --- #
############################################
def agente_redator(localizacao, preferencias, rotas_planejadas):
    otimizador = Agent(
        name="agente_otimizador_rotas",
        model="gemini-2.0-flash",
        instruction=f"""
        Você é um especialista em otimização de rotas de caminhada e corrida.
        Com base nas rotas planejadas ({rotas_planejadas}) para a localização ({localizacao}) e as preferências do usuário ({preferencias}), sua função é:
        - Refinar as rotas propostas, considerando fatores como elevação (para adequar ao nível de dificuldade), segurança (evitando áreas de risco), e beleza cênica (se solicitado).
        - Sugerir variações das rotas planejadas, como atalhos ou extensões, para diferentes níveis de energia ou tempo disponível.
        - Se aplicável, fornecer informações sobre transporte público para acessar diferentes pontos das rotas.
        - Apresentar as rotas de forma clara e concisa, destacando os principais benefícios de cada uma.
        """,
        description="Agente que otimiza e detalha as rotas.",
    )
    entrada_do_agente_redator = f"Localização: {localizacao}\nPreferências: {preferencias}\nRotas planejadas: {rotas_planejadas}"
    rotas_otimizadas = call_agent(otimizador, entrada_do_agente_redator)
    return rotas_otimizadas

#################################################
# --- Agente 4: Avaliador de Rotas e Feedback --- #
#################################################
def agente_revisor(localizacao, preferencias, rotas_otimizadas):
    avaliador = Agent(
        name="agente_avaliador_rotas",
        model="gemini-2.0-flash",
        instruction=f"""
        Você é um avaliador de rotas de caminhada e corrida com foco na experiência do usuário.
        Revise as rotas otimizadas ({rotas_otimizadas}) criadas para a localização ({localizacao}) e as preferências do usuário ({preferencias}). Sua tarefa é:
        - Avaliar se as rotas propostas atendem de forma clara e eficaz às preferências e necessidades do usuário.
        - Verificar se as informações fornecidas são práticas, úteis e fáceis de entender.
        - Sugerir melhorias na descrição das rotas, como adicionar informações sobre o tipo de calçamento, disponibilidade de sombra, ou pontos de atenção.
        - Fornecer um resumo conciso das melhores opções de rotas, destacando os principais atrativos de cada uma.
        """,
        description="Agente que avalia as rotas e fornece feedback.",
    )
    entrada_do_agente_revisor = f"Localização: {localizacao}\nPreferências: {preferencias}\nRotas otimizadas: {rotas_otimizadas}"
    feedback_rotas = call_agent(avaliador, entrada_do_agente_revisor)
    return feedback_rotas

data_de_hoje = date.today().strftime("%d/%m/%Y") # Mantendo, embora não seja diretamente usado agora

print("🏃‍♀️ Iniciando o Sistema Inteligente de Geração de Rotas Personalizadas 🏃‍♂️")

# --- Obter a Localização e Preferências do Usuário ---
localizacao = input("📍 Por favor, digite a sua LOCALIZAÇÃO para buscar rotas: ")
preferencias = input("👟 Quais são suas PREFERÊNCIAS para a rota? (ex: distância, nível de dificuldade, tipo de paisagem): ")

# Inserir lógica do sistema de agentes ################################################
if not localizacao:
    print("Você não digitou uma localização. Por favor, tente novamente.")
elif not preferencias:
    print("Você não digitou suas preferências. Por favor, tente novamente.")
else:
    print(f"Maravilha! Vamos encontrar rotas personalizadas para {localizacao} com suas preferências: {preferencias}")

    locais_encontrados = agente_buscador(localizacao, preferencias)
    print("\n--- 🗺️ Resultado do Agente 1 (Buscador de Locais) ---\n")
    display(md(locais_encontrados))
    print("---------------------------------------------------------------------")

    rotas_planejadas = agente_planejador(localizacao, preferencias, locais_encontrados)
    print("\n--- 🗺️ Resultado do Agente 2 (Planejador de Rotas) ---\n")
    display(md(rotas_planejadas))
    print("---------------------------------------------------------------------")

    rotas_otimizadas = agente_redator(localizacao, preferencias, rotas_planejadas)
    print("\n--- 🗺️ Resultado do Agente 3 (Otimizador de Rotas) ---\n")
    display(md(rotas_otimizadas))
    print("---------------------------------------------------------------------")

    feedback_rotas = agente_revisor(localizacao, preferencias, rotas_otimizadas)
    print("\n--- 🗺️ Resultado do Agente 4 (Avaliador de Rotas) ---\n")
    display(md(feedback_rotas))
    print("---------------------------------------------------------------------")